// Mocks generated by Mockito 5.4.4 from annotations
// in lamov_flutter_app/test/features/home/presentation/cubit/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:lamov_flutter_app/core/data/error/error.dart' as _i6;
import 'package:lamov_flutter_app/core/domain/common/model/base_model.dart'
    as _i10;
import 'package:lamov_flutter_app/core/domain/common/model/genre_model.dart'
    as _i7;
import 'package:lamov_flutter_app/core/domain/common/model/movie_model.dart'
    as _i11;
import 'package:lamov_flutter_app/core/domain/usecase.dart' as _i8;
import 'package:lamov_flutter_app/feature/home/domain/param/get_movies_pagination_param.dart'
    as _i12;
import 'package:lamov_flutter_app/feature/home/domain/repository/home_repository.dart'
    as _i2;
import 'package:lamov_flutter_app/feature/home/domain/usecase/get_movie_genres_use_case.dart'
    as _i4;
import 'package:lamov_flutter_app/feature/home/domain/usecase/get_movies_discover_use_case.dart'
    as _i15;
import 'package:lamov_flutter_app/feature/home/domain/usecase/get_movies_now_playing_use_case.dart'
    as _i9;
import 'package:lamov_flutter_app/feature/home/domain/usecase/get_movies_popular_use_case.dart'
    as _i13;
import 'package:lamov_flutter_app/feature/home/domain/usecase/get_movies_top_rated_use_case.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeRepository_0 extends _i1.SmartFake
    implements _i2.HomeRepository {
  _FakeHomeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetMovieGenresUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieGenresUseCase extends _i1.Mock
    implements _i4.GetMovieGenresUseCase {
  MockGetMovieGenresUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.GenreModel>>> call(
          _i8.NoParams? param) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.GenreModel>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.GenreModel>>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.GenreModel>>>);
}

/// A class which mocks [GetMoviesNowPlayingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMoviesNowPlayingUseCase extends _i1.Mock
    implements _i9.GetMoviesNowPlayingUseCase {
  MockGetMoviesNowPlayingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>> call(
          _i12.GetMoviesPaginationParam? param) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>>.value(
            _FakeEither_1<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
      ) as _i5
          .Future<_i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>>);
}

/// A class which mocks [GetMoviesPopularUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMoviesPopularUseCase extends _i1.Mock
    implements _i13.GetMoviesPopularUseCase {
  MockGetMoviesPopularUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>> call(
          _i12.GetMoviesPaginationParam? param) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>>.value(
            _FakeEither_1<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
      ) as _i5
          .Future<_i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>>);
}

/// A class which mocks [GetMoviesTopRatedUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMoviesTopRatedUseCase extends _i1.Mock
    implements _i14.GetMoviesTopRatedUseCase {
  MockGetMoviesTopRatedUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>> call(
          _i12.GetMoviesPaginationParam? param) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>>.value(
            _FakeEither_1<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
      ) as _i5
          .Future<_i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>>);
}

/// A class which mocks [GetMoviesDiscoverUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMoviesDiscoverUseCase extends _i1.Mock
    implements _i15.GetMoviesDiscoverUseCase {
  MockGetMoviesDiscoverUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>> call(
          _i12.GetMoviesPaginationParam? param) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>>.value(
            _FakeEither_1<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
      ) as _i5
          .Future<_i3.Either<_i6.Failure, _i10.BaseModel<_i11.MovieModel>>>);
}
